version: '2.4'
services:

  explorer:
    image: ghcr.io/ledgerhq/blockchain-explorer/explorer-btc:latest
    environment:
      JAVA_OPTS: -Xmx2G
      EXPLORER_TICKER: btc_testnet
      EXPLORER_NAME: E2E BTC like explorer
      EXPLORER_CASSANDRA_KEYSPACE: btc_like
      EXPLORER_CASSANDRA_CONTACT_POINTS: cassandra
      EXPLORER_CASSANDRA_PORT: 9042
      EXPLORER_RPC_URI: http://praline:28443/rpc
      EXPLORER_RPC_BASIC_AUTH: none
    ports:
      - 20000:20000
    deploy:
      restart_policy:
        condition: on-failure

  indexer:
    image: ghcr.io/ledgerhq/blockchain-explorer/indexer-btc:latest
    environment:
      JAVA_OPTS: -Xmx2G
      INDEXER_TICKER: btc
      INDEXER_NAME: E2E BTC like indexer
      INDEXER_CASSANDRA_KEYSPACE: btc_like
      INDEXER_CASSANDRA_CONTACT_POINTS: cassandra
      INDEXER_CASSANDRA_PORT: 9042
      INDEXER_RPC_URI: http://praline:28443/rpc
      INDEXER_RPC_BASIC_AUTH: none
      INDEXER_MAXIMUM_DELAY_ALLOWED: 1000000000000000
      INDEXER_MAXIMUM_GAP_ALLOWED: 10000000000
    ports:
      - 11000:11000
    deploy:
      restart_policy:
        condition: on-failure

  cassandra:
    image: bitnami/cassandra:3.11.8
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
      BITNAMI_DEBUG: "true"
    ports:
      - 9042:9042
    volumes:
      - ./tooling/btc_schema.cql:/docker-entrypoint-initdb.d/btc_schema.cql

  praline:
    image: ghcr.io/ledgerhq/blockchain-explorer/praline:latest
    environment:
      RPC_HOST: http://btcliked
    ports:
      - 28443:28443
    depends_on:
      - btcliked

  btcliked:
    image: ruimarinho/bitcoin-core:0.19.1
    command: -regtest=1 -rpcallowip=0.0.0.0/0 -rpcbind=0.0.0.0 -rpcuser=user -rpcpassword=pass -fallbackfee=0.001
    ports:
      - 18443:18443

  redis:
    image: redis
    ports:
      - "6379:6379"

  postgres-server-ssl:
    image: postgres
    environment:
      POSTGRES_DB: wallet_daemon_test
      POSTGRES_USER: ledger
      POSTGRES_PASSWORD: ledger_secret
    volumes:
      - ./tooling/database/postgres/local_init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    command: -c "ssl=on" -c "ssl_key_file=/etc/ssl/private/ssl-cert-snakeoil.key" -c "ssl_cert_file=/etc/ssl/certs/ssl-cert-snakeoil.pem"

  wallet-daemon:
    image: ghcr.io/ledgerhq/ledger-wallet-daemon:2.11
    environment:
      CORE_DATABASE_ENGINE: postgres
      CORE_PG_HOST: postgres-server-ssl
      CORE_PG_USER: ledger
      CORE_PG_PWD: ledger_secret
      CORE_PG_DB_NAME_PREFIX: wd_
      WALLET_DAEMON_DB_NAME: wallet_daemon
      REDIS_HOST: redis
      REDIS_PORT: 6379
      WALLET_BTC_TESTNET_EXPLORER_ENDPOINT: http://explorer
      WALLET_BTC_TESTNET_EXPLORER_PORT: 20000
      WALLET_BTC_TESTNET_EXPLORER_VERSION: v3
    entrypoint: /app/run.sh -Dscala.concurrent.context.numThreads=x8 -Dscala.concurrent.context.maxThreads=x8
    ports:
      - "9200:9200"
    depends_on:
      - postgres-server-ssl
      - redis
