name: CI

on:
  create:
    tag:
      - "v*"
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Test, build, lint
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Build
        run: npm install

      - name: Test
        run: npm test

      - name: Lint
        run: npm run lint
